### ISSUE TITLE
Nginx starting before generate configs can fail if we already have invalid confis

### ISSUE THREAD

**Issue by igormukhingmailcom** [William-Yeh/ansible-nginx#2]
Hi, William.

Could we (I can prepare commit if you will merge) remove this line?
https://github.com/William-Yeh/ansible-nginx/blob/master/tasks/use-apt.yml#L45

It causes error at the middle of playbook if config is broken (not valid).
And it can't update by new one untill we remove it manually.
We should use `notify` here I think.

PS: Thanks for cool role :)

**Comment by William-Yeh** [comment]
Hi,

Do you mean, first undertake a dry-run like the following:

```
nginx -t -c new-config-file
```

and then start the nginx when the dry run passes?

**Comment by igormukhingmailcom** [comment]
I mean start it at the end by notifying [services](https://github.com/William-Yeh/ansible-nginx/blob/master/handlers/main.yml) and not running in the middle of script. 

Current behavior:
Failed config > starting nginx > error .... > generate new config without error (but this never be reached due to error)

Suggested behavior:
Failed config > notify to start > generate new config without error > start at the end

WDYT?

**Comment by William-Yeh** [comment]
I add an option `nginx_start` to let users specify whether to `service nginx start` automatically.

Please check if this meets your needs:
https://github.com/William-Yeh/ansible-nginx/tree/optionally-start
